version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres_auth
      - kafka
      - mongo

  portfolio-service:
    build: ./portfolio-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres_order
      - kafka
      - mongo

  real-time-service:
    build: ./real-time-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - kafka

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres_auth:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432" # Changed port mapping
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data

  postgres_order:
    image: postgres:latest
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432" # Changed port mapping
    volumes:
      - postgres-order-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-auth-data:
  postgres-order-data:
